///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String date1 = 'assets/images/date 1.png';
  static const String group = 'assets/images/Group.svg';
  static const String group2 = 'assets/images/Group 2.png';
  static const String logo = 'assets/images/logo.png';
  static const String markazElAmal = 'assets/images/Markaz ElAmal.png';
  static const String selectdoc1 = 'assets/images/select doc 1.png';
  static const String selectdoctor1 = 'assets/images/select doctor 1.png';
  static const String splash = 'assets/images/splash.png';
  static const String splash2 = 'assets/images/splash 2.png';
  static const String settings = 'assets/images/settings.svg';
  static const String homePageHeaderImage =
      'assets/images/Home_header_Image.png';
  static const String heart = 'assets/images/heart.png';
}
